"""Report serialization and human-readable output."""
from __future__ import annotations

import html
import json
from pathlib import Path

from .models import ScanReport


def to_dict(report: ScanReport) -> dict:
    return report.to_dict(include_files=True)


def write_json(report: ScanReport, path: str | Path) -> None:
    Path(path).write_text(json.dumps(to_dict(report), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _safe_markdown_cell(value: str) -> str:
    value = value.replace("\r\n", " ").replace("\r", " ").replace("\n", " ").replace("\t", " ")
    escaped = html.escape(value, quote=False)
    entities = {ord(char): f"&#{ord(char)};" for char in "\\|`*_{}[]!#>~:@"}
    return escaped.translate(entities)


def markdown(report: ScanReport) -> str:
    lines = ["# ModRelease Studio report", "", f"- Source: {_safe_markdown_cell(report.target)}", f"- Profile: `{report.profile}`",
             f"- SHA-256: `{report.sha256}`", f"- Files scanned: **{report.file_count}** ({report.total_bytes:,} bytes)",
             f"- Status: **{report.status}**", f"- Findings: **{report.errors} errors, {report.warnings} warnings**", ""]
    if not report.findings:
        lines += ["## Result", "", "No configured release checks reported a problem.", ""]
    else:
        lines += ["## Findings", "", "| Severity | Check | File | Details |", "|---|---|---|---|"]
        for item in report.findings:
            detail = _safe_markdown_cell(item.message)
            path = _safe_markdown_cell(item.path or "—")
            lines.append(f"| {item.severity} | `{item.code}` | {path} | {detail} |")
        lines.append("")
    lines += ["---", "Generated by [ModRelease Studio](https://github.com/GhosTnever-lkm/modrelease-studio).", ""]
    return "\n".join(lines)


def write_markdown(report: ScanReport, path: str | Path) -> None:
    Path(path).write_text(markdown(report), encoding="utf-8")
